CREATE TABLE JTD_BOND_ALL
(
  "SCENARIO_DATE" DATE,
  "MV_UNIT"       NUMBER,
  "ISIN"          VARCHAR2(12),
  "COUNTRY_CODE"  VARCHAR2(2)
);

CREATE TABLE JTD_BOND_FX
(
  "SCENARIO_DATE" DATE,
  "MV_UNIT"       NUMBER,
  "ISIN"          VARCHAR2(12),
  "COUNTRY_CODE"  VARCHAR2(2)
);

CREATE TABLE JTD_BOND_IR
(
  "SCENARIO_DATE" DATE,
  "MV_UNIT"       NUMBER,
  "ISIN"          VARCHAR2(12),
  "COUNTRY_CODE"  VARCHAR2(2)
);
